# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-11 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBackend', '0002_auto_20170211_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='locations',
        ),
        migrations.AddField(
            model_name='path',
            name='pathLocations',
            field=models.ManyToManyField(related_name='pathLocations', to='AppBackend.Location'),
        ),
    ]
