# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBackend', '0003_auto_20170211_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='description',
            field=models.TextField(default='Opis nase lokacije je tukaj'),
            preserve_default=False,
        ),
    ]
