# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-15 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBackend', '0004_path_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(default='Pre\u0161ernov trg'),
            preserve_default=False,
        ),
    ]
